# 25 10 27 Adicionando Tolkien na Base

In [30]:
from pathlib import Path
folder_raw = "data/tolkien_raw_pt1"
folder_txt = "data/tolkien_txt_pt1"

Path(folder_txt).mkdir(parents=True, exist_ok=True)
print(f"{folder_raw=}")
epubs = list(Path(folder_raw).glob("*.epub"))
print(f"{len(epubs)=}")
epubs[:2]

folder_raw='data/tolkien_raw_pt1'
len(epubs)=10

[WindowsPath('data/tolkien_raw_pt1/Tolkien, J R R - As Aventuras de Tom Bombadil e Outras Histórias (2012, Exilado) - libgen.li.epub'),
 WindowsPath('data/tolkien_raw_pt1/Tolkien, J. R. R. - Mestre Gil de Ham (2012, Exilado) - libgen.li.epub')]

In [ ]:
import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup

def epub_to_txt(path_epub, folder_txt):
    book = epub.read_epub(path_epub)
    title = book.get_metadata('DC', 'title')[0][0]

    content = []
    for item in book.get_items():
        if item.get_type() == ebooklib.ITEM_DOCUMENT:
            soup = BeautifulSoup(item.get_content(), 'html.parser')
            text = soup.get_text()
            content.append(text)

    path_txt = folder_txt + "/" + title + ".txt"
    # if not Path(path_txt).exists():
    #     with open(path_txt, 'w', encoding='utf-8') as f:
    #         f.write('\n'.join(content))
    # else:
    #     print(f"Skipping {path_txt}, already exists.")

    metadata = {
        'title': title,
        'author': book.get_metadata('DC', 'creator')[0][0],
        "path_raw": str(path_epub),
        "path_txt": path_txt,
        "text_raw_len": len('\n'.join(content)),
    }
    print(f"{metadata=}")

    return metadata


metadatas = []
for file in epubs:
    print(f"\nConverting {file}...")
    try:
        metadata = epub_to_txt(file, folder_txt)
        metadatas.append(metadata)
    except Exception as e:
        print(f"Error converting {file}: {e}")

Converting data\tolkien_raw_pt1\Tolkien, J R R - As Aventuras de Tom Bombadil e Outras Histórias (2012, Exilado) - libgen.li.epub...
metadata={'title': 'As Aventuras de Tom Bombadil e Outras Histórias', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\Tolkien, J R R - As Aventuras de Tom Bombadil e Outras Histórias (2012, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/As Aventuras de Tom Bombadil e Outras Histórias.txt', 'text_raw_len': 147339}

Converting data\tolkien_raw_pt1\Tolkien, J. R. R. - Mestre Gil de Ham (2012, Exilado) - libgen.li.epub...
metadata={'title': 'Mestre Gil de Ham', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\Tolkien, J. R. R. - Mestre Gil de Ham (2012, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/Mestre Gil de Ham.txt', 'text_raw_len': 222675}

Converting data\tolkien_raw_pt1\Tolkien, J. R. R. - Roverandom (2012, Exilado) - libgen.li.epub...
metadata={'title': 'Roverandom', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\Tolkien, J. R. R. - Roverandom (2012, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/Roverandom.txt', 'text_raw_len': 216018}

Converting data\tolkien_raw_pt1\Tolkien, J.R.R. - A história de Kullervo (2016, WMF Martins Fontes) - libgen.li.epub...
metadata={'title': 'A história de Kullervo', 'author': 'J.R.R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\Tolkien, J.R.R. - A história de Kullervo (2016, WMF Martins Fontes) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/A história de Kullervo.txt', 'text_raw_len': 259391}

Converting data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J R R - A Sociedade do Anel (2011, Exilado) - libgen.li.epub...
metadata={'title': 'A Sociedade do Anel', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 1 ] Tolkien, J R R - A Sociedade do Anel (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/A Sociedade do Anel.txt', 'text_raw_len': 1063099}

Converting data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J R R - As Duas Torres (2011, Exilado) - libgen.li.epub...
metadata={'title': 'As Duas Torres', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 1 ] Tolkien, J R R - As Duas Torres (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/As Duas Torres.txt', 'text_raw_len': 894629}

Converting data\tolkien_raw_pt1\[Fantasia 3 ] Tolkien, J R R - O Retorno do Rei (2011, Exilado) - libgen.li.epub...
metadata={'title': 'O Retorno do Rei', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 3 ] Tolkien, J R R - O Retorno do Rei (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/O Retorno do Rei.txt', 'text_raw_len': 1072304}

Converting data\tolkien_raw_pt1\[Fantasia 4 ] Tolkien, J R R - O hobbit (2011, Exilado) - libgen.li.epub...
metadata={'title': 'O Hobbit', 'author': 'J.R.R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 4 ] Tolkien, J R R - O hobbit (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/O Hobbit.txt', 'text_raw_len': 534363}

Converting data\tolkien_raw_pt1\[Fantasia 5 ] Tolkien, J R R - O Silmarillion (2011, Exilado) - libgen.li.epub...
metadata={'title': 'O Silmarillion', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 5 ] Tolkien, J R R - O Silmarillion (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/O Silmarillion.txt', 'text_raw_len': 877037}

Converting data\tolkien_raw_pt1\[Fantasia 8 ] Tolkien, J R R - Os Filhos de Hurin (2011, Exilado) - libgen.li.epub...
metadata={'title': 'Os Filhos de Húrin', 'author': 'J. R. R. Tolkien', 'path_epub': 'data\\tolkien_raw_pt1\\[Fantasia 8 ] Tolkien, J R R - Os Filhos de Hurin (2011, Exilado) - libgen.li.epub', 'path_txt': 'data/tolkien_txt_pt1/Os Filhos de Húrin.txt', 'text_raw_len': 404046}

In [36]:
import pandas as pd

df = pd.DataFrame(metadatas)

In [61]:
df.sort_values("title")

,title,author,path_raw,path_txt,text_raw_len,text,text_len,text_clean,text_clean_len
4,A Sociedade do Anel,Tolkien,"data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J ...",data/tolkien_txt_pt1/A Sociedade do Anel.txt,1063099,CAPÍTULO I: UMA FESTA MUITO ESPERADA\n\n\nQua...,1005814,CAPÍTULO I: UMA FESTA MUITO ESPERADA\nQuando o...,1005177
3,A história de Kullervo,Tolkien,"data\tolkien_raw_pt1\Tolkien, J.R.R. - A histó...",data/tolkien_txt_pt1/A história de Kullervo.txt,259391,A HISTÓRIA DE KULLERVO\n\n\nA história de Hont...,120933,A HISTÓRIA DE KULLERVO\nA história de Honto Ta...,120792
0,As Aventuras de Tom Bombadil e Outras Histórias,Tolkien,"data\tolkien_raw_pt1\Tolkien, J R R - As Avent...",data/tolkien_txt_pt1/As Aventuras de Tom Bomba...,147339,\nAS AVENTURAS DE TOM BOMBADIL\n \n1\nO velho ...,139084,AS AVENTURAS DE TOM BOMBADIL\n1\nO velho Tom B...,138676
5,As Duas Torres,Tolkien,"data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J ...",data/tolkien_txt_pt1/As Duas Torres.txt,894629,CAPÍTULO I : A PARTIDA DE BOROMIR\n\nAragorn ...,890161,CAPÍTULO I : A PARTIDA DE BOROMIR\nAragorn sub...,889868
1,Mestre Gil de Ham,Tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Mestr...",data/tolkien_txt_pt1/Mestre Gil de Ham.txt,222675,Mestre Gil de Ham\n \n \n\n \nAEGIDIUS de Hamm...,142649,Mestre Gil de Ham\nAEGIDIUS de Hammo morava na...,142296
7,O Hobbit,Tolkien,"data\tolkien_raw_pt1\[Fantasia 4 ] Tolkien, J ...",data/tolkien_txt_pt1/O Hobbit.txt,534363,CAPÍTULO I: UMA FESTA INESPERADA\n \nNuma toc...,529011,CAPÍTULO I: UMA FESTA INESPERADA\nNuma toca no...,528622
6,O Retorno do Rei,Tolkien,"data\tolkien_raw_pt1\[Fantasia 3 ] Tolkien, J ...",data/tolkien_txt_pt1/O Retorno do Rei.txt,1072304,CAPÍTULO I: MINAS TIRITH\n\nPippin espiou de ...,921413,CAPÍTULO I: MINAS TIRITH\nPippin espiou de den...,921075
8,O Silmarillion,Tolkien,"data\tolkien_raw_pt1\[Fantasia 5 ] Tolkien, J ...",data/tolkien_txt_pt1/O Silmarillion.txt,877037,AINULINDALË\n\n\nA Música dos Ainur\n\n\nHavi...,731961,"AINULINDALE\nA Música dos Ainur\nHavia Eru, o ...",731587
9,Os Filhos de Húrin,Tolkien,"data\tolkien_raw_pt1\[Fantasia 8 ] Tolkien, J ...",data/tolkien_txt_pt1/Os Filhos de Húrin.txt,404046,CAPÍTULO I: A INFÂNCIA DE TÚRIN\n\n\nHador Ca...,337826,CAPÍTULO I: A INFÂNCIA DE TÚRIN\nHador Cabeça ...,337762
2,Roverandom,Tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Rover...",data/tolkien_txt_pt1/Roverandom.txt,216018,ROVERANDOM\n\nEra uma vez um cãozinho que se c...,141647,ROVERANDOM\nEra uma vez um cãozinho que se cha...,141617

In [60]:
df = df.rename(columns={"path_epub": "path_raw"})

In [66]:
df["author"] = df["author"].str.replace("J. R. R. |J.R.R. ", "", regex=True).str.lower()

In [73]:
df["extension"] = "epub"
df["class"] = df["author"]
df["subtitle"] = ""

In [69]:
df["text"] = df["path_txt"].apply(lambda x: Path(x).read_text(encoding='utf-8'))
df["text_len"] = df["text"].str.len()

In [ ]:
from src.prep import clean_text2

df["text_clean"] = df.text.apply(clean_text2)
df["text_clean_len"] = df["text_clean"].str.len()

In [87]:
import numpy as np

print("Train test splits and weights...")

df["weights"] = df.text_clean_len
df["weights"] = df["weights"] / df["weights"].sum()
print(df.groupby([ 'author']).weights.sum())

split_frac = 0.85
index_eval = df.sample(frac=1-split_frac, random_state=1, weights="weights").index
df["split"] = pd.Series(df.index.isin(index_eval)).map({False: "train", True: "eval"})

Train test splits and weights...
author
tolkien    1.0
Name: weights, dtype: float64

In [88]:
df.sort_values("text_clean_len")

,title,author,path_raw,path_txt,text_raw_len,text,text_len,text_clean,text_clean_len,extension,class,subtitle,weights,split
3,A história de Kullervo,tolkien,"data\tolkien_raw_pt1\Tolkien, J.R.R. - A histó...",data/tolkien_txt_pt1/A história de Kullervo.txt,259391,A HISTÓRIA DE KULLERVO\n\n\nA história de Hont...,120933,A HISTÓRIA DE KULLERVO\nA história de Honto Ta...,120792,epub,tolkien,,0.024366,train
0,As Aventuras de Tom Bombadil e Outras Histórias,tolkien,"data\tolkien_raw_pt1\Tolkien, J R R - As Avent...",data/tolkien_txt_pt1/As Aventuras de Tom Bomba...,147339,\nAS AVENTURAS DE TOM BOMBADIL\n \n1\nO velho ...,139084,AS AVENTURAS DE TOM BOMBADIL\n1\nO velho Tom B...,138676,epub,tolkien,,0.027973,train
2,Roverandom,tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Rover...",data/tolkien_txt_pt1/Roverandom.txt,216018,ROVERANDOM\n\nEra uma vez um cãozinho que se c...,141647,ROVERANDOM\nEra uma vez um cãozinho que se cha...,141617,epub,tolkien,,0.028566,train
1,Mestre Gil de Ham,tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Mestr...",data/tolkien_txt_pt1/Mestre Gil de Ham.txt,222675,Mestre Gil de Ham\n \n \n\n \nAEGIDIUS de Hamm...,142649,Mestre Gil de Ham\nAEGIDIUS de Hammo morava na...,142296,epub,tolkien,,0.028703,train
9,Os Filhos de Húrin,tolkien,"data\tolkien_raw_pt1\[Fantasia 8 ] Tolkien, J ...",data/tolkien_txt_pt1/Os Filhos de Húrin.txt,404046,CAPÍTULO I: A INFÂNCIA DE TÚRIN\n\n\nHador Ca...,337826,CAPÍTULO I: A INFÂNCIA DE TÚRIN\nHador Cabeça ...,337762,epub,tolkien,,0.068132,train
7,O Hobbit,tolkien,"data\tolkien_raw_pt1\[Fantasia 4 ] Tolkien, J ...",data/tolkien_txt_pt1/O Hobbit.txt,534363,CAPÍTULO I: UMA FESTA INESPERADA\n \nNuma toc...,529011,CAPÍTULO I: UMA FESTA INESPERADA\nNuma toca no...,528622,epub,tolkien,,0.106631,eval
8,O Silmarillion,tolkien,"data\tolkien_raw_pt1\[Fantasia 5 ] Tolkien, J ...",data/tolkien_txt_pt1/O Silmarillion.txt,877037,AINULINDALË\n\n\nA Música dos Ainur\n\n\nHavi...,731961,"AINULINDALE\nA Música dos Ainur\nHavia Eru, o ...",731587,epub,tolkien,,0.147573,train
5,As Duas Torres,tolkien,"data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J ...",data/tolkien_txt_pt1/As Duas Torres.txt,894629,CAPÍTULO I : A PARTIDA DE BOROMIR\n\nAragorn ...,890161,CAPÍTULO I : A PARTIDA DE BOROMIR\nAragorn sub...,889868,epub,tolkien,,0.179500,eval
6,O Retorno do Rei,tolkien,"data\tolkien_raw_pt1\[Fantasia 3 ] Tolkien, J ...",data/tolkien_txt_pt1/O Retorno do Rei.txt,1072304,CAPÍTULO I: MINAS TIRITH\n\nPippin espiou de ...,921413,CAPÍTULO I: MINAS TIRITH\nPippin espiou de den...,921075,epub,tolkien,,0.185795,train
4,A Sociedade do Anel,tolkien,"data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J ...",data/tolkien_txt_pt1/A Sociedade do Anel.txt,1063099,CAPÍTULO I: UMA FESTA MUITO ESPERADA\n\n\nQua...,1005814,CAPÍTULO I: UMA FESTA MUITO ESPERADA\nQuando o...,1005177,epub,tolkien,,0.202760,train

In [89]:
df_v20 = pd.read_parquet("data/df_full_encoded_v20.pq")

In [90]:
renames = {
    "file": "path_txt"
}
columns = [
    'title',
    'author',
    "class",
    "subtitle",

    'path_txt', 
    "extension",
    'text',
    'text_len',
    'text_clean',
    "split",
    "weights",
]
df_v20_merge = df_v20.rename(columns=renames)[columns]
df_v20_merge.iloc[0]

title                                               O Conscrito
author                                                lovecraft
class                                                   Poesias
subtitle
path_txt                                                    nan
extension                                                  None
text          Sou um trabalhador e vivo em paz,\nNem mais sá...
text_len                                                   1648
text_clean    Sou um trabalhador e vivo em paz,\nNem mais sá...
split                                                      eval
weights                                                0.000074
Name: 0, dtype: object

In [ ]:
df_full = pd.concat([df, df_v20_merge], ignore_index=True)
df_full

,title,author,path_raw,path_txt,text_raw_len,text,text_len,text_clean,text_clean_len,extension,class,subtitle,weights,split
0,As Aventuras de Tom Bombadil e Outras Histórias,tolkien,"data\tolkien_raw_pt1\Tolkien, J R R - As Avent...",data/tolkien_txt_pt1/As Aventuras de Tom Bomba...,147339.0,\nAS AVENTURAS DE TOM BOMBADIL\n \n1\nO velho ...,139084,AS AVENTURAS DE TOM BOMBADIL\n1\nO velho Tom B...,138676.0,epub,tolkien,,0.027973,train
1,Mestre Gil de Ham,tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Mestr...",data/tolkien_txt_pt1/Mestre Gil de Ham.txt,222675.0,Mestre Gil de Ham\n \n \n\n \nAEGIDIUS de Hamm...,142649,Mestre Gil de Ham\nAEGIDIUS de Hammo morava na...,142296.0,epub,tolkien,,0.028703,train
2,Roverandom,tolkien,"data\tolkien_raw_pt1\Tolkien, J. R. R. - Rover...",data/tolkien_txt_pt1/Roverandom.txt,216018.0,ROVERANDOM\n\nEra uma vez um cãozinho que se c...,141647,ROVERANDOM\nEra uma vez um cãozinho que se cha...,141617.0,epub,tolkien,,0.028566,train
3,A história de Kullervo,tolkien,"data\tolkien_raw_pt1\Tolkien, J.R.R. - A histó...",data/tolkien_txt_pt1/A história de Kullervo.txt,259391.0,A HISTÓRIA DE KULLERVO\n\n\nA história de Hont...,120933,A HISTÓRIA DE KULLERVO\nA história de Honto Ta...,120792.0,epub,tolkien,,0.024366,train
4,A Sociedade do Anel,tolkien,"data\tolkien_raw_pt1\[Fantasia 1 ] Tolkien, J ...",data/tolkien_txt_pt1/A Sociedade do Anel.txt,1063099.0,CAPÍTULO I: UMA FESTA MUITO ESPERADA\n\n\nQua...,1005814,CAPÍTULO I: UMA FESTA MUITO ESPERADA\nQuando o...,1005177.0,epub,tolkien,,0.202760,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,A Busca de Iranon,lovecraft,NaN,nan,NaN,Para dentro da cidade granítica de Teloth pera...,15793,Para dentro da cidade granítica de Teloth pera...,NaN,None,Ciclo dos Sonhos,,0.000640,train
185,Astrophobos,lovecraft,NaN,nan,NaN,"No céu da meia-noite a se incendiar,\natravés ...",1495,"No céu da meia-noite a se incendiar,\natravés ...",NaN,None,Poesias,,0.000071,train
186,Os Outros Deuses,lovecraft,NaN,nan,NaN,No topo dos mais altos cumes do planeta habita...,11914,No topo dos mais altos cumes do planeta habita...,NaN,None,Ciclo dos Sonhos,,0.000482,train
187,Ar Frio,lovecraft,NaN,nan,NaN,Você pede que eu explique por que tenho medo d...,21447,Você pede que eu explique por que tenho medo d...,NaN,None,Miscelânea,,0.000833,eval
188,Ibid,lovecraft,NaN,nan,NaN,"… conforme afirma Ibid em sua famosa obra, Vid...",10864,"... conforme afirma Ibid em sua famosa obra, V...",NaN,None,Miscelânea,,0.000506,train

In [104]:
df_full = df_full[['title',
 'author',
 'extension',
 'class',
 'subtitle',
 'path_raw',
 'path_txt',
 'text_raw_len',
 'text',
 'text_len',
 'text_clean',
 'text_clean_len',
 'weights',
 'split']]

In [107]:
from src.prep import clean_text2
df_full["text_len"] = df_full["text"].str.len()
df_full["text_clean"] = df_full.text.apply(clean_text2)
df_full["text_clean_len"] = df_full["text_clean"].str.len()

In [108]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           189 non-null    object
 1   author          189 non-null    object
 2   extension       75 non-null     object
 3   class           189 non-null    object
 4   subtitle        124 non-null    object
 5   path_raw        10 non-null     object
 6   path_txt        189 non-null    object
 7   text_raw_len    10 non-null     float64
 8   text            189 non-null    object
 9   text_len        189 non-null    int64
 10  text_clean      189 non-null    object
 11  text_clean_len  189 non-null    int64
 12  weights         189 non-null    float64
 13  split           189 non-null    object
dtypes: float64(2), int64(2), object(10)
memory usage: 20.8+ KB

In [123]:
df_full["weights"] = df_full["text_clean_len"].clip(0, 500_000)
df_full["weights"] = df_full["weights"] / df_full["weights"].sum()

In [124]:
df_full.sample(10).filter(regex="author|weights")

        author   weights
89        king  0.013520
57   lovecraft  0.000217
52        king  0.013520
37   lovecraft  0.000033
136       king  0.013520
81        king  0.008659
78        king  0.013520
95        king  0.013520
32   lovecraft  0.001972
99        king  0.013520

In [126]:
df_full.groupby(['author', "split"]).weights.sum()

author     split
king       eval     0.136570
           train    0.683017
lovecraft  eval     0.023014
           train    0.065976
tolkien    eval     0.027039
           train    0.064384
Name: weights, dtype: float64

In [127]:
df_full[["author", "split"]].value_counts().sort_index()

author     split
king       eval     11
           train    54
lovecraft  eval     38
           train    76
tolkien    eval      2
           train     8
Name: count, dtype: int64

In [130]:
df_full = df_full.sample(frac=1).reset_index(drop=True)

In [132]:
df_full.to_parquet("data/df_full_v21.pq")

# 25 10 29 Novo tokenizer

In [ ]:
# https://github.com/huggingface/notebooks/blob/main/examples/tokenizer_training.ipynb

In [173]:
df_full = pd.read_parquet("data/df_full_v21.pq")

In [155]:
text_full = "\n\n\n".join(df_full.query("split=='train'").sample(frac=1).text_clean.to_list())

In [156]:
print(f"{text_full[:2_000]=}")
print(f"{len(text_full)=}")

text_full[:2_000]='66 College St., Providence R. I.\n27 e 28 de junho de 1934\n— Prezado R. E. H:\nComo você pôde notar pelo meu cartão postal, cheguei a casa pontualmente outra vez e encontrei a aranha em excelente condição. Esse monstro agora adorna a prateleira de meu museu, fazendo companhia à cobra da Flórida e outras peças exóticas — incluindo as cascavéis, as quais me colocam em dívida com você. Por certo prefiro vê-la ali a salvo, numa garrafa, que se arrastando em meus aposentos!\nA minha viagem, não preciso dizer, foi profundamente aprazível. Uma vez que provavelmente descreví St. Augustine em detalhes em 1931, não preciso ver o território novamente — exceto para ressaltar o quão potente é o feitiço imaginativo que jaz em torno daquelas casas antigas e daquele secular e melancólico forte. Aqui há um lugar que já passava dos 50 anos de idade quando o primeiro peregrino chegou a Plymouth. Nessa ocasião, vi uma atração adicional de grande interesse — um velho cemitério indígena recentemente aflorado na localidade do primitivo vilarejo nativo ao norte da cidade. Os esqueletos jazem lado a lado, com os pés apontando a leste, sendo permanentemente preservados em suas posições originais. O trabalho de escavação foi muito cuidadoso — cada esqueleto e a terra em volta são protegidos por uma murada de cimento. Oportunamente um grande museu será erigido na área aflorada. A aparência dessa descoberta — que foi feita apenas poucas semanas antes que eu a visse — é, de fato, muito esquisita. Pela postura dos corpos, fica claro que estes foram sepultados sob os auspícios dos padres franciscanos — por volta do ano de 1600.\n* * *\nQuanto a meus ideais de governo, você certamente me entendeu errado. Você diz que não odeia o desenvolvimento humano, e ainda assim escarnece do ideal simplório de um governo restrito a homens que são propriamente treinados para desempenhar suas tarefas, sabendo o que fazem. Além disso, você diz que, se meu ideal de governo fosse o da força, eu iria — ou poderia — queima'
len(text_full)=55070430

In [157]:
batch_size = int(7e7)

def batch_iterator():
    for i in range(0, len(text_full), batch_size):
        yield text_full[i:i+batch_size]

len_batches = len(list(batch_iterator()))
lens_batches = [len(b) for b in batch_iterator()]
print(f"{len_batches=}")
print(f"{lens_batches=}")
for i, b in enumerate(batch_iterator()):
    print(i, b[:50])

len_batches=1
lens_batches=[55070430]
0 66 College St., Providence R. I.
27 e 28 de junho

In [158]:
from transformers import AutoTokenizer
 
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.is_fast

True

In [159]:
new_tokenizer = tokenizer.train_new_from_iterator(batch_iterator(), vocab_size=50257)

In [160]:
new_tokenizer.save_pretrained("artifacts/tokenizers/gpt2_ptbr_50k_v2")

('artifacts/tokenizers/gpt2_ptbr_50k_v2\\tokenizer_config.json',
 'artifacts/tokenizers/gpt2_ptbr_50k_v2\\special_tokens_map.json',
 'artifacts/tokenizers/gpt2_ptbr_50k_v2\\vocab.json',
 'artifacts/tokenizers/gpt2_ptbr_50k_v2\\merges.txt',
 'artifacts/tokenizers/gpt2_ptbr_50k_v2\\added_tokens.json',
 'artifacts/tokenizers/gpt2_ptbr_50k_v2\\tokenizer.json')

In [161]:
from transformers import AutoTokenizer

loaded_tokenizer = AutoTokenizer.from_pretrained("artifacts/tokenizers/gpt2_ptbr_50k_v2")
assert new_tokenizer.get_vocab() == loaded_tokenizer.get_vocab()

In [162]:
# Get info
print(f"{new_tokenizer.vocab_size=}")
print(f"{new_tokenizer.model_max_length=}")
vocab = new_tokenizer.get_vocab()
print(f"{len(vocab)=}")
# sorted
vocab_sorted = sorted([(token, s) for s,token in vocab.items()])

new_tokenizer.vocab_size=50257
new_tokenizer.model_max_length=1024
len(vocab)=50257

In [163]:
print(vocab_sorted[:10])
print(vocab_sorted[250:260])
print(vocab_sorted[260:270])
print(vocab_sorted[-10:])

[(0, '<|endoftext|>'), (1, '!'), (2, '"'), (3, '#'), (4, '$'), (5, '%'), (6, '&'), (7, "'"), (8, '('), (9, ')')]
[(250, 'Ľ'), (251, 'ľ'), (252, 'Ŀ'), (253, 'ŀ'), (254, 'Ł'), (255, 'ł'), (256, 'Ń'), (257, 'Ġd'), (258, 'Ġe'), (259, 'Ġa')]
[(260, 'ra'), (261, 'Ġp'), (262, 'Ġc'), (263, 'Ġde'), (264, 'Ġs'), (265, 'qu'), (266, 'nt'), (267, 'os'), (268, 'Ġm'), (269, 'er')]
[(50247, '86'), (50248, '96'), (50249, 'Ag'), (50250, 'Amo'), (50251, 'Aaron'), (50252, 'Brien'), (50253, 'Cin'), (50254, 'Cress'), (50255, 'Chil'), (50256, 'CADOR')]

In [164]:
print("Testando tokenizer...")
tokens = loaded_tokenizer(text_full[:1_000_000]).input_ids
print(f"{len(text_full[:1_000_000])=} {len(tokens)=}")
compression_ratio = len(text_full[:1_000_000]) / len(tokens)
print(f"{compression_ratio=}")

Testando tokenizer...

Token indices sequence length is longer than the specified maximum sequence length for this model (236935 > 1024). Running this sequence through the model will result in indexing errors

len(text_full[:1_000_000])=1000000 len(tokens)=236935
compression_ratio=4.220566822124211

In [165]:
tokens = loaded_tokenizer(text_full[:2_000]).input_ids
loaded_tokenizer.model_max_length = 100
tokens2 = loaded_tokenizer(text_full[:2_000]).input_ids
assert tokens == tokens2

In [166]:
test_text = "Não. Além. Caçada. Bônus gênero. — ª° ‡. í á â ^ à"
tokens = new_tokenizer(test_text).input_ids
decoded_text = new_tokenizer.decode(tokens)
print(f"{decoded_text=}")
print(f"{tokens=}")

decoded_text='Não. Além. Caçada. Bônus gênero. — ª° ‡. í á â ^ à'
tokens=[1262, 14, 2820, 14, 2311, 3627, 14, 401, 24257, 12409, 14, 317, 221, 127, 104, 127, 109, 221, 288, 95, 14, 5867, 805, 3730, 221, 62, 479]

In [167]:
test_text = "Não. Além. Caçada. Bônus gênero. — ª° ‡. í á â ^ à"
tokens = loaded_tokenizer(test_text).input_ids
decoded_text = loaded_tokenizer.decode(tokens)
print(f"{decoded_text=}")
print(f"{tokens=}")

decoded_text='Não. Além. Caçada. Bônus gênero. — ª° ‡. í á â ^ à'
tokens=[1262, 14, 2820, 14, 2311, 3627, 14, 401, 24257, 12409, 14, 317, 221, 127, 104, 127, 109, 221, 288, 95, 14, 5867, 805, 3730, 221, 62, 479]

In [168]:
new_tokenizer.special_tokens_map

{'bos_token': '<|endoftext|>',
 'eos_token': '<|endoftext|>',
 'unk_token': '<|endoftext|>'}

In [174]:
from tqdm import tqdm

tqdm.pandas()
print("Encoding input texts...")
encode = lambda s: new_tokenizer(s, truncation=False).input_ids
df_full["text_encoded"] = df_full.text_clean.progress_apply(lambda x: encode(x))
df_full["text_encoded_len"] =  df_full.text_encoded.apply(len)
print(f"{df_full.text_encoded_len.describe()=}")

Encoding input texts...

100%|██████████| 189/189 [00:55<00:00,  3.38it/s]

df_full.text_encoded_len.describe()=count       189.000000
mean      80087.560847
std      116832.521712
min          60.000000
25%        1473.000000
50%        6739.000000
75%      155861.000000
max      601185.000000
Name: text_encoded_len, dtype: float64

In [175]:
print("\nChars/Tokens statistics:")
len_corpus = int(df_full["text_clean_len"].sum()) / 1e6
len_splits = (df_full.groupby("split").text_len.sum() / 1e6).to_dict()
print("Chars:")
print(f"{len_corpus=} {len_splits=} M chars")

len_corpus = int(df_full["text_encoded_len"].sum()) / 1e6
len_splits = (df_full.groupby("split").text_encoded_len.sum() / 1e6).to_dict()
print("Tokens:")
print(f"{len_corpus=} {len_splits=} M tokens")

compression_ratio = (df_full["text_len"].sum()) / (df_full["text_encoded_len"].sum())
print(f"Overall compression ratio (chars/tokens): {compression_ratio:.2f}")

Chars/Tokens statistics:
Chars:
len_corpus=68.180796 len_splits={'eval': 13.120932, 'train': 55.184733} M chars
Tokens:
len_corpus=15.136549 len_splits={'eval': 2.905144, 'train': 12.231405} M tokens
Overall compression ratio (chars/tokens): 4.51

In [176]:
print("Saving encoded to path_input_encoded...")
df_full.to_parquet("data/df_full_encoded_v21.pq")

Saving encoded to path_input_encoded...

In [179]:
df_full

,title,author,extension,class,subtitle,path_raw,path_txt,text_raw_len,text,text_len,text_clean,text_clean_len,weights,split,text_encoded,text_encoded_len
0,Na Catacumba,lovecraft,None,Miscelânea,,None,nan,NaN,"(Dedicado a C. W. Smith,\ncuja sugestão gerou ...",21874,"(Dedicado a C. W. Smith,\ncuja sugestão gerou ...",21877,0.000592,eval,"[8, 36, 1298, 6793, 259, 366, 14, 722, 14, 781...",4370
1,Ar Frio,lovecraft,None,Miscelânea,,None,nan,NaN,Você pede que eu explique por que tenho medo d...,21447,Você pede que eu explique por que tenho medo d...,21449,0.000580,eval,"[2670, 12145, 285, 431, 29133, 348, 285, 1433,...",4397
2,Ibid,lovecraft,None,Miscelânea,,None,nan,NaN,"… conforme afirma Ibid em sua famosa obra, Vid...",10864,"... conforme afirma Ibid em sua famosa obra, V...",10863,0.000294,train,"[428, 7742, 8442, 41678, 326, 473, 14021, 6901...",2549
3,Último turno 2016 epub,king,epub,king,None,None,data\king_txt_v3\king\Último turno 2016 epub.txt,NaN,Para Thomas Harris\n\n\n\n\n\n\n10 DE ABRIL DE...,674546,Para Thomas Harris\n10 DE ABRIL DE 2009:\nMART...,674316,0.013520,eval,"[4890, 8678, 6740, 199, 5891, 1817, 45849, 44,...",153635
4,Nyarlathotep,lovecraft,None,Ciclo de Cthulhu,,None,nan,NaN,Nyarlathotep o caos sorrateiro… eu sou o últim...,7665,Nyarlathotep o caos sorrateiro... eu sou o últ...,7671,0.000207,train,"[46, 24090, 275, 14292, 34577, 428, 431, 1333,...",1473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,O Chamado de Cthulhu,lovecraft,None,Ciclo de Cthulhu,,None,nan,NaN,(Encontrado entre os documentos do falecido\nF...,77445,(Encontrado entre os documentos do falecido\nF...,77422,0.002093,train,"[8, 16987, 725, 767, 365, 9642, 320, 11242, 19...",15255
185,A Torre Negra 8 O Vento Através Da Fechadura v...,king,epub,torre_negra,None,None,data\king_txt_v3\torre_negra\A Torre Negra 8 O...,NaN,A Torre Negra: O Vento Através Da Fechadura - ...,571565,A Torre Negra: O Vento Através Da Fechadura - ...,528268,0.013520,train,"[33, 4853, 6262, 26, 372, 18369, 20876, 1188, ...",119879
186,Laeta; um Lamento,lovecraft,None,Poesias,,None,nan,NaN,Tombam tristes os salgueiros junto à margem do...,2250,Tombam tristes os salgueiros junto à margem do...,2250,0.000061,train,"[5903, 22847, 14973, 365, 26818, 1849, 479, 46...",577
187,A Busca Onírica por Kadath,lovecraft,None,Ciclo dos Sonhos,,None,nan,NaN,Por três vezes Randolph Carter sonhou com a ci...,267206,Por três vezes Randolph Carter sonhou com a ci...,267210,0.007225,train,"[1985, 994, 910, 5621, 3999, 14705, 304, 259, ...",52096
188,Novembro de 63 2013 epub,king,epub,king,None,None,data\king_txt_v3\king\Novembro de 63 2013 epub...,NaN,"Para Zelda\n\n Oi, querida, bem-vinda à festa...",1503850,"Para Zelda\n Oi, querida, bem-vinda à festa.\n...",1502998,0.013520,train,"[4890, 19281, 199, 4214, 12, 4257, 12, 570, 13...",338420